name: Download Video to File

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'הדבק כאן את הקישור לבדיקה'
        required: true
        default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'

jobs:
  download-video:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Save Cookies File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download Video File
        run: |
          echo "Downloading video..."
          yt-dlp --cookies cookies.txt -f "b[ext=mp4]/b" --recode-video mp4 -o "video.mp4" "${{ github.event.inputs.youtube_url }}"

      - name: Upload Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: video.mp4
